#!/bin/bash
#
# tools/rpm/build-rpm.sh          (RUN IN THE BUILD VM -- never in dom0)
#
# usage: build-rpm.sh [--version V] [--release R] [--sign KEYID] [--outdir DIR]
#
# Build the dom0 half of this project into one signed, auditable .rpm.
#
# Everything that ends up in the package comes from manifest.txt. The spec is
# GENERATED from it rather than maintained beside it, so there is no second
# list to drift out of step -- and the generated spec is written to the output
# directory so you can read exactly what was built.
#
# The package is deliberately inert:
#
#   - no %pre/%post/%preun/%postun/%pretrans/%posttrans. Nothing executes in
#     dom0 at install time. rpm unpacks files and stops.
#   - AutoReqProv: no. No dependency generator runs over the shell scripts, so
#     installing cannot drag anything else into dom0.
#   - _binary_payload w.ufdio. The payload is UNCOMPRESSED, for the same
#     reason the tar workflow this replaces was uncompressed: it keeps a
#     second parser (zstd) out of dom0's install path and makes a
#     decompression bomb arithmetically impossible.
#   - __os_install_post nil. rpmbuild's brp-* policy scripts are disabled, so
#     the payload is byte-identical to the reviewed tree. Left enabled,
#     brp-mangle-shebangs silently rewrites the shebang of every executable.
#
# The last thing this script does is run vpn-rpm-audit against its own output
# and fail if the audit does. Building and checking are separate programs on
# purpose: the audit asks the finished package what it contains rather than
# taking this script's word for it.

set -euo pipefail

PROG=build-rpm.sh
die() { echo "$PROG: $*" >&2; exit 1; }

HERE=$(cd "$(dirname "$0")" && pwd)
ROOT=$(cd "$HERE/../.." && pwd)
TREE="$ROOT/dom0"
MANIFEST="$HERE/manifest.txt"

NAME="qubes-vpn-dvm-dom0"
VERSION="1.0.0"
RELEASE="1"
KEYID=""
OUTDIR="$HOME/rpmbuild-vpn"

while [ $# -gt 0 ]; do
    case "$1" in
        --version) VERSION="${2:-}"; shift 2 ;;
        --release) RELEASE="${2:-}"; shift 2 ;;
        --sign)    KEYID="${2:-}"; shift 2 ;;
        --outdir)  OUTDIR="${2:-}"; shift 2 ;;
        -h|--help) sed -n '3,6p' "$0"; exit 0 ;;
        *)         die "unknown argument '$1'" ;;
    esac
done

[ "$(hostname)" != "dom0" ] || die "build in the build VM, not dom0"
[ -d "$TREE" ]      || die "no dom0 tree at $TREE"
[ -f "$MANIFEST" ]  || die "no manifest at $MANIFEST"
command -v rpmbuild >/dev/null || die "rpmbuild not found -- dnf install rpm-build"
[ -z "$KEYID" ] || command -v rpmsign >/dev/null || die "rpmsign not found -- dnf install rpm-sign"

# Version must be something rpm can order, or an upgrade will not upgrade.
[[ "$VERSION" =~ ^[0-9][0-9A-Za-z.]*$ ]] || die "bad version '$VERSION'"
[[ "$RELEASE" =~ ^[0-9][0-9A-Za-z.]*$ ]] || die "bad release '$RELEASE'"

rm -rf "$OUTDIR"
mkdir -p "$OUTDIR"/{SPECS,BUILD,BUILDROOT,RPMS,SOURCES}

# --- read the manifest --------------------------------------------------------

declare -a M_MODE M_PATH M_FLAGS
while read -r mode relpath flags; do
    [ -n "${mode:-}" ] || continue
    [[ "$mode" =~ ^[0-7]{4}$ ]] || die "bad mode '$mode' for '${relpath:-?}' in manifest"
    # case, not "[[ ]] && die": under set -e a bare "test && die" exits the
    # script with status 1 whenever the test is FALSE, which is the normal path.
    case "$relpath" in /*) die "manifest paths are relative to dom0/: '$relpath'" ;; esac
    case "/$relpath/" in */../*) die "manifest path contains '..': $relpath" ;; esac
    M_MODE+=("$mode"); M_PATH+=("$relpath"); M_FLAGS+=("${flags:-}")
done < <(grep -vE '^[[:space:]]*(#|$)' "$MANIFEST")

[ "${#M_PATH[@]}" -gt 0 ] || die "manifest is empty"

# Every non-directory entry must exist in the source tree BEFORE rpmbuild
# starts, so a missing file is a clear error here rather than a confusing one
# from the middle of a build.
for i in "${!M_PATH[@]}"; do
    case "${M_FLAGS[$i]}" in
        *dir*) continue ;;
    esac
    [ -f "$TREE/${M_PATH[$i]}" ] || die "manifest lists ${M_PATH[$i]}, but $TREE/${M_PATH[$i]} does not exist"
done

# --- generate the spec --------------------------------------------------------

SPEC="$OUTDIR/SPECS/$NAME.spec"

{
cat <<SPECHEAD
# GENERATED by tools/rpm/build-rpm.sh from tools/rpm/manifest.txt
# $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Do not edit. Edit manifest.txt and rebuild.

# Uncompressed payload: no second parser, and no decompression bomb.
%define _binary_payload w.ufdio
%define _build_id_links none
%global debug_package %{nil}

# Payload must be BYTE-IDENTICAL to the reviewed source tree.
#
# Fedora's rpmbuild runs a set of "brp-" policy scripts over the buildroot
# after %install. One of them, brp-mangle-shebangs, rewrites #!/bin/bash to
# #!/usr/bin/bash in every file carrying the execute bit. The rewrite is
# harmless in itself -- /bin is a symlink to /usr/bin -- but it means the
# package ships bytes that are not the bytes you read, which is precisely the
# guarantee this project depends on. vpn-rpm-audit check [8] catches it and
# fails the build.
#
# Disabling the whole post-install stage is safe here: this is a noarch
# package of shell scripts and text with no binaries to strip, no man pages
# to compress and no Python to bytecompile. Nothing should touch the payload.
%global __os_install_post %{nil}

Name:           $NAME
Version:        $VERSION
Release:        $RELEASE
Summary:        dom0 tooling for firewalled disposable VPN qubes
License:        GPL-2.0-only
BuildArch:      noarch

# No dependency generator runs over the packaged shell scripts. Installing
# this must never pull anything into dom0.
AutoReqProv:    no

%description
Salt states, qrexec policy and dom0 commands that build a firewalled
disposable VPN qube from a single configuration file.

This package contains no install-time scriptlets. It unpacks files and does
nothing else; every action is taken later, deliberately, by running one of
the vpn-* commands as your own user.

# No %prep, %build or %check: there is nothing to compile. The payload is the
# reviewed source tree, copied verbatim.

%install
rm -rf %{buildroot}
SPECHEAD

for i in "${!M_PATH[@]}"; do
    p="${M_PATH[$i]}"; m="${M_MODE[$i]}"
    case "${M_FLAGS[$i]}" in
        *dir*) printf 'install -d -m %s %%{buildroot}/%s\n' "$m" "$p" ;;
        *)     printf 'install -D -m %s %%{_sourcedir}/dom0/%s %%{buildroot}/%s\n' "$m" "$p" "$p" ;;
    esac
done

echo
echo "%files"
echo "%defattr(-,root,root,-)"

for i in "${!M_PATH[@]}"; do
    p="${M_PATH[$i]}"; m="${M_MODE[$i]}"; f="${M_FLAGS[$i]}"
    attr="%attr($m,root,root)"
    case "$f" in
        *dir*)    printf '%%dir %s /%s\n' "$attr" "$p" ;;
        *config*) printf '%%config(noreplace) %s /%s\n' "$attr" "$p" ;;
        *)        printf '%s /%s\n' "$attr" "$p" ;;
    esac
done

cat <<'SPECTAIL'

%changelog
* Thu Jan 01 1970 build-rpm.sh <nobody@localhost> - 0-0
- Generated package; see git history for real changes.
SPECTAIL
} > "$SPEC"

# --- build --------------------------------------------------------------------
# The source tree is handed over read-only via _sourcedir. rpmbuild only ever
# copies out of it.

echo "$PROG: building $NAME-$VERSION-$RELEASE"
rpmbuild \
    --define "_topdir $OUTDIR" \
    --define "_sourcedir $ROOT" \
    -bb "$SPEC" > "$OUTDIR/build.log" 2>&1 \
    || { tail -30 "$OUTDIR/build.log"; die "rpmbuild failed -- full log at $OUTDIR/build.log"; }

RPMFILE=$(find "$OUTDIR/RPMS" -name '*.rpm' -type f)
[ -n "$RPMFILE" ] || die "rpmbuild produced no package"
[ "$(wc -l <<<"$RPMFILE")" -eq 1 ] || die "rpmbuild produced more than one package"

echo "$PROG: built $RPMFILE"

# --- sign ---------------------------------------------------------------------

if [ -n "$KEYID" ]; then
    echo "$PROG: signing with $KEYID"
    rpmsign --define "_gpg_name $KEYID" --addsign "$RPMFILE" \
        || die "signing failed"
else
    echo "$PROG: NOT SIGNED (no --sign given) -- the audit will fail check [2]"
fi

# --- audit --------------------------------------------------------------------
# Deliberately the last step and deliberately a separate program. If this
# fails, the package does not leave the build VM.

echo
# Invoked through bash rather than as "$HERE/vpn-rpm-audit", so a checkout
# that lost the execute bit fails the AUDIT rather than failing to run it --
# the difference between "package rejected" and "package silently unchecked".
#
# "|| rc=$?", not a bare call followed by "rc=$?": set -e would exit on a
# failing audit before the status could be read, skipping the cleanup below.
auditargs=(--tree "$TREE" --manifest "$MANIFEST")
[ -z "$KEYID" ] || auditargs+=(--key "$KEYID")

rc=0
bash "$HERE/vpn-rpm-audit" "${auditargs[@]}" "$RPMFILE" || rc=$?

echo
if [ "$rc" -eq 0 ]; then
    echo "Package ready:"
    echo "  $RPMFILE"
    echo
    echo "Pull it into dom0 with (run this IN dom0):"
    echo "  qvm-run --pass-io --no-gui <this-qube> 'cat $RPMFILE' > ~/$(basename "$RPMFILE")"
else
    echo "AUDIT FAILED -- deleting the package so it cannot be copied by mistake."
    rm -f "$RPMFILE"
fi
exit "$rc"
